### ISSUE TITLE
404 error on xdao

### ISSUE THREAD

**Issue by tainmar** [guillim/wallet2pseudo#1]
```json
{
  error: {
    code: 404,
    message: "Document "projects/xdao-app/databases/(default)/documents/networks/56/dao/0x33e74c591a5c3b062997463f41ca1a81225b1ae8" not found.",
    status: "NOT_FOUND"
  }
}
```

on URL : https://firestore.googleapis.com/v1/projects/xdao-app/databases/(default)/documents/networks/56/dao/0x33e74c591a5c3b062997463f41ca1a81225b1ae8

**Comment by guillim** [comment]
Thanks for raising the first issue. Our team will do everything it can to help you in your journey with Wallet2PSeudo. 
We cannot reproduce your error. For us to investigate, please provide the original URL you go to.

**Comment by tainmar** [comment]
This needs to be reopened, bug is still, see attached video :
https://www.loom.com/share/3205ddc86d48478f8d1695b4e7a8e7e4

(please note that I also tried with all my extensions disabled, except Metamask & Wallet2Pseudo)

**Comment by tainmar** [comment]
Ok so without any explication, when I re-enabled all my extensions, it finally worked !

**Comment by tainmar** [comment]
Oh no... I cannot click on the button now, but the page is correctly displayed. Very weird.

**Comment by guillim** [comment]
Probably related to `html` re-writing. There might be some callback based on addresses written in the `html`, that are changed by the extension, causing the _forever load_. 

The only way I see to avoid this issue is to change completely the way this extension works : add some hover event instead of re-writing `html`.

What do you think ?

**Comment by tainmar** [comment]
Hover would be nice but not that efficient.
Maybe a shortcut like `cmd-G` or something like this to change all the addresses.
So always happen after the page is fully loaded
